export const userData = [
  {
    name: "Olivia Rhye",
    noOfBoots: 3,
    role: "Admin",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 2,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 4,
    role: "Admin",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 2,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 2,
    role: "Manager",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 5,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Inactive",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 4,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 4,
    role: "Admin",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 4,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 2,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 1,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
  {
    name: "Olivia Rhye",
    noOfBoots: 3,
    role: "Operator",
    lastLogin: "2023-01-03",
    status: "Active",
  },
];

export const robootData = [
  {
    name: "Transaction Flow",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Admin",
    status: "Active",
  },
  {
    name: "Automation framework",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Roboot",
    status: "Active",
  },
  {
    name: "Automation framework 2.1",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Admin",
    status: "Active",
  },
  {
    name: "Date copy excel",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Manager",
    status: "Active",
  },
  {
    name: "Automation framework 2.1",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Browser loading calculator",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Inactive",
  },
  {
    name: "Automation framework 2.1",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Data entry and report",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Admin",
    status: "Active",
  },
  {
    name: "Automation framework 2.1",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Data entry and report",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Browser loading calculator",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Automation framework",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
  {
    name: "Data entry and report",
    version: "Version 1.1.1",
    userMonth: "17 hrs",
    assignTo: "Operator",
    status: "Active",
  },
];
